# Generated by Django 3.1.6 on 2021-02-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_column='user_id', help_text='User ID number in Telegram', max_length=20, verbose_name='User ID')),
                ('first_name', models.CharField(db_column='first_name', help_text='Contact first Name', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(db_column='last_name', help_text='Contact last name', max_length=50, verbose_name='Last Name')),
                ('phone_number', models.CharField(db_column='phone_number', help_text='Contact phone number', max_length=20, verbose_name='Phone Number')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
