# Generated by Django 3.1.6 on 2021-02-18 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatbody_chatheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatheader',
            name='company',
            field=models.CharField(db_column='company', help_text='Header company', max_length=50, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='chatheader',
            name='report_db',
            field=models.TextField(db_column='report_db', help_text='Header report_db', null=True, verbose_name='Report DB'),
        ),
        migrations.AlterField(
            model_name='chatheader',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contact'),
        ),
    ]
