# Generated by Django 3.2 on 2021-07-16 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210218_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotContent',
            fields=[
                ('botcontent_id', models.AutoField(db_column='id', help_text='botcontent_id', primary_key=True, serialize=False, verbose_name='botcontent_id')),
                ('name', models.CharField(db_column='name', help_text='name', max_length=120, verbose_name='Nome')),
                ('description', models.CharField(db_column='description', help_text='description', max_length=120, verbose_name='Descricao')),
                ('sql', models.TextField(db_column='sql', help_text='Instrução SQL', null=True, verbose_name='SQL')),
                ('visualization_type', models.CharField(db_column='visualization_type', help_text='Tipo de visualização (Gráfico ou tabela)', max_length=250, null=True, verbose_name='Tipo de Visualização')),
                ('properties', models.TextField(db_column='properties', help_text='configuration', null=True, verbose_name='Configuração ou Propriedades')),
            ],
            options={
                'db_table': 'bot_content',
            },
        ),
        migrations.CreateModel(
            name='BotHeader',
            fields=[
                ('botheader_id', models.AutoField(db_column='id', help_text='botheader_id', primary_key=True, serialize=False, verbose_name='botheader_id')),
                ('company_id', models.IntegerField(db_column='company', help_text='company', verbose_name='Empresa')),
                ('first_name', models.CharField(db_column='first_name', help_text='Primeiro Nome', max_length=120, verbose_name='first_name')),
                ('last_name', models.CharField(db_column='last_name', help_text='Sobrenome', max_length=120, verbose_name='last_name')),
                ('description', models.CharField(db_column='description', help_text='description', max_length=120, verbose_name='Descricao')),
                ('configuration', models.TextField(db_column='configuration', help_text='configuration', null=True, verbose_name='Configuração')),
                ('dbname', models.TextField(db_column='dbname', help_text='dbname', null=True, verbose_name='dbname')),
            ],
            options={
                'db_table': 'bot_header',
            },
        ),
        migrations.CreateModel(
            name='MultiServiceIntegrator',
            fields=[
                ('nome_msi', models.TextField(db_column='nome_msi', help_text='nome_msi', primary_key=True, serialize=False, verbose_name='nome_msi')),
                ('flab_msi', models.TextField(db_column='flab_msi', help_text='flab_msi', verbose_name='flab_msi')),
                ('sql_msi', models.TextField(db_column='sql_msi', help_text='sql_msi', verbose_name='sql_msi')),
            ],
            options={
                'db_table': 'multiserviceintegrator',
            },
        ),
        migrations.RemoveField(
            model_name='chatheader',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_id',
            field=models.IntegerField(db_column='contact_id', default=1, help_text='contact_id', verbose_name='contact_id'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(db_column='phone_number', help_text='phone_number', max_length=20, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_id',
            field=models.AutoField(db_column='id', help_text='user_id', primary_key=True, serialize=False, verbose_name='user_id'),
        ),
        migrations.DeleteModel(
            name='ChatBody',
        ),
        migrations.DeleteModel(
            name='ChatHeader',
        ),
        migrations.AddField(
            model_name='botheader',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', help_text='user_id foreignkey', on_delete=django.db.models.deletion.PROTECT, to='core.contact', verbose_name='user_id'),
        ),
        migrations.AddField(
            model_name='botcontent',
            name='botheader_id',
            field=models.ForeignKey(db_column='botheader_id', help_text='botheader_id', on_delete=django.db.models.deletion.PROTECT, to='core.botheader', verbose_name='botheader_id'),
        ),
    ]
