# Generated by Django 3.2 on 2021-07-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210716_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(db_column='id', help_text='user_id', primary_key=True, serialize=False, verbose_name='user_id'),
        ),
    ]
