# Generated by Django 3.2 on 2021-07-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contact_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botheader',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='botheader',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(db_column='first_name', default='', help_text='Primeiro Nome', max_length=120, verbose_name='first_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(db_column='last_name', default='', help_text='Sobrenome', max_length=120, verbose_name='last_name'),
            preserve_default=False,
        ),
    ]
